import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "CMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" >
      <body className="font-mono">
        {children}
        <Footer />
        <Navbar />
        <Toaster />
      </body>
    </html>
  );
}
